runtime: python39 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
    MYSQL_USER: 'root'
    MYSQL_PASSWORD: ''
    MYSQL_DB: 'Airbnb'
    MYSQL_HOST: '34.133.97.105'

handlers:
-url: /script
static_dir: static/script

-url: /styles
static_dir: static/styles